### ISSUE TITLE
Add isup.me

### ISSUE THREAD

**Issue by TheOneBehindYou** [arantius/resurrect-pages#36] opened 2018-04-28 11:49 UTC
Hi,
I'm using the fork https://github.com/Albirew/resurrect-pages-isup-edition but since the last update it is no longer displayed in contextual menu (right click) so I'm planning to use your original. But there is one function very useful in the forked version that was the reason for me to use it, it's the possibility to test the site with https://downforeveryoneorjustme.com/
Could you please add this to your add-on or explain me how to do it by myself? It would be greatly appreciated.
I hope my english is not too bad and you understand my request.
Thanks. Regards.

**Comment by arantius** [comment] 2018-04-29 19:06
Dupe of #2.  I don't plan on doing this.

**Closed by arantius** 2018-04-29 19:06 UTC
